import "./globals.css";
import ClientWrapper from "@/components/ClientWrapper"; // Handle state in a separate component

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen ">
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
